### ISSUE TITLE
rubocop導入

### ISSUE THREAD

**Issue by taishi0202** [web-academia/qa-rails-ec-training-broom#19]
静的コード解析のGemを導入すること。

Gemfileに、
- rubocop
- rubocop-rails
- rubocop-rspec

の3つのgemを入れること。

onkcopリポジトリ( https://github.com/onk/onkcop )のconfig下にある、`rspec.yml`, `rails.yml`, `rubocop.yml`の3つのファイルたちをコピーする。

`config/rubocop/`というフォルダを作って、コピーしたファイルたちをその下にペーストすること。

設定ファイル `.rubocop.yml` を作成し、以下のように入力すること。

```
require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - "config/rubocop/rails.yml"
  - "config/rubocop/rubocop.yml"
  - "config/rubocop/rspec.yml"

AllCops:
  TargetRubyVersion: *.*.*
  TargetRailsVersion: *.*.*.*
```
